services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - db
        networks:
            - laravel
        ports:
            - "9000:9000"
        command: php-fpm

    web:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "${APP_PORT:-8080}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
